# Generated by Django 4.2.10 on 2024-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_musicprovider_providertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicprovider',
            name='providertype',
            field=models.IntegerField(default=1),
        ),
    ]
