# Generated by Django 4.2.10 on 2024-02-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_is_dj_user_is_provider_musicprovider_dj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreid', models.AutoField(primary_key=True, serialize=False)),
                ('genrename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('labelid', models.AutoField(primary_key=True, serialize=False)),
                ('labelname', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('songid', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('soundcloud', models.URLField(blank=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.label')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.musicprovider')),
            ],
        ),
    ]
