# Generated by Django 4.2.10 on 2024-02-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_music_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='releasedate',
            field=models.DateField(null=True),
        ),
    ]
