# Generated by Django 4.2.10 on 2024-02-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.label'),
        ),
    ]
